/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    orders: Order;
    reviews: Review;
    favorites: Favorite;
    pages: Page;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    favorites: FavoritesSelect<false> | FavoritesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'site-settings': SiteSetting;
    cities: City;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Phone number for delivery contact
   */
  phone?: string | null;
  role?: ('admin' | 'user' | 'manager') | null;
  /**
   * Выберите коллекции, к которым пользователь будет иметь доступ. Если не выбрано ничего, доступ ко всем коллекциям (только для админов).
   */
  accessCollections?: ('users' | 'categories' | 'products' | 'media' | 'orders' | 'reviews' | 'pages')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Уникальное значение (английское) для категории. Используется внутри кода. ДОЛЖНО БЫТЬ ОДНО СЛОВО! НЕЛЬЗЯ ПРОБЕЛОВ
   */
  value: string;
  title: string;
  /**
   * Чем меньше число, тем выше в списке. По умолчанию 0. Можно использовать отрицательные числа.
   */
  order?: number | null;
  /**
   * Если не выбрано — это основная категория
   */
  parent?: (number | null) | Category;
  /**
   * Иконка нужна только для основных категорий
   */
  icon?: (number | null) | Media;
  /**
   * Загрузите обложку для подкатегории (видны в каталоге)
   */
  coverImage?: (number | null) | Media;
  /**
   * SEO заголовок для подкатегории. Поддерживает переменные города: /city (именительный), /city/r (родительный), /city/p (предложный)
   */
  seoTitle?: string | null;
  /**
   * SEO описание для подкатегории. Поддерживает переменные города: /city, /city/r, /city/p
   */
  seoDescription?: string | null;
  /**
   * Подробное описание подкатегории с форматированием. Поддерживает переменные города: /city (именительный: Москва), /city/r (родительный: Москвы), /city/p (предложный: в Москве)
   */
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Дополнительный контент, который будет отображаться после списка товаров. Поддерживает переменные города: /city, /city/r, /city/p
   */
  contentAfter?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Название услуги. Поддерживает переменные города для автоматической замены: /city (Москва), /city/r (Москвы), /city/p (в Москве).
   */
  title: string;
  /**
   * Название услуги на странице услуги и в SEO метаданных. Поддерживает переменные города: /city (Москва), /city/r (Москвы), /city/p (в Москве).
   */
  pageTitle?: string | null;
  price: number;
  /**
   * Выберите только категорию, без подкатегорий
   */
  category: (number | Category)[];
  /**
   * Выберите подкатегорию
   */
  subCategory: number | Category;
  /**
   * Загрузите основное изображение товара (необязательно)
   */
  image?: (number | null) | Media;
  /**
   * Описание для SEO. Также поддерживает переменные города: /city, /city/r, /city/p - они заменятся на город пользователя в соответствующем падеже.
   */
  description?: string | null;
  /**
   * Если включено, товар будет иметь отдельную страницу. Если выключено, при клике на товар сразу откроется форма бронирования.
   */
  hasProductPage?: boolean | null;
  /**
   * Доступно только когда включена страничка товара
   */
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Обновляется автоматически при добавлении отзыва
   */
  averageRating?: number | null;
  reviewsCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Просто уникальный номер заказа(для разработки, можно не обращать внимания)
   */
  orderNumber: string;
  /**
   * Услуга
   */
  product: number | Product;
  /**
   * Имя клиента
   */
  customerName: string;
  /**
   * пользователь (если был зарегестрирован, то привязывается)
   */
  user?: (number | null) | User;
  status: 'pending' | 'waiting_call' | 'cancelled';
  /**
   * Customer phone number
   */
  customerPhone: string;
  /**
   * Additional notes or comments
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  product: number | Product;
  user: number | User;
  rating: number;
  comment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites".
 */
export interface Favorite {
  id: number;
  user: number | User;
  product: number | Product;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Уникальный slug, не менять!
   */
  slug: string;
  /**
   * Название странички (в поисковике будет)
   */
  title: string;
  /**
   * Описание, которое в поисковике.
   */
  description: string;
  /**
   * Это контент страницы
   */
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'favorites';
        value: number | Favorite;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  role?: T;
  accessCollections?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  value?: T;
  title?: T;
  order?: T;
  parent?: T;
  icon?: T;
  coverImage?: T;
  seoTitle?: T;
  seoDescription?: T;
  content?: T;
  contentAfter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  pageTitle?: T;
  price?: T;
  category?: T;
  subCategory?: T;
  image?: T;
  description?: T;
  hasProductPage?: T;
  content?: T;
  averageRating?: T;
  reviewsCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  product?: T;
  customerName?: T;
  user?: T;
  status?: T;
  customerPhone?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  product?: T;
  user?: T;
  rating?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites_select".
 */
export interface FavoritesSelect<T extends boolean = true> {
  user?: T;
  product?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Основные настройки сайта и контактная информация. Если вы ставите изображение (в слайдере) сразу с текстом, то не добавляйте просто текст. Но будьте аккуратны, проверьте как ваш текст (на картинке) выглядит на мобилках и на пк.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Описание для главной страницы. Поддерживает переменные города: /city (именительный: Москва), /city/r (родительный: Москвы), /city/p (предложный: в Москве). Они автоматически заменятся на город пользователя.
   */
  homeContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Изображения для слайдера на главной странице
   */
  slider?: {
    /**
     * Добавьте изображения для слайдера
     */
    slides?:
      | {
          /**
           * Изображение для слайда (рекомендуемый размер: 1280x200px)
           */
          image: number | Media;
          /**
           * Основной заголовок слайда. Можете использовать переменные города: /city (именительный: Москва), /city/r (родительный: Москвы), /city/p (предложный: в Москве). Они автоматически заменятся на город пользователя.
           */
          title?: string | null;
          /**
           * Дополнительный текст под заголовком. Также поддерживает переменные города: /city, /city/r, /city/p - будут заменены на соответствующее склонение города.
           */
          subtitle?: string | null;
          /**
           * Выберите цвет заголовка для лучшей читаемости
           */
          titleColor?: ('black' | 'white' | 'gray' | 'red' | 'blue' | 'green' | 'yellow') | null;
          /**
           * Выберите цвет подзаголовка для лучшей читаемости
           */
          subtitleColor?: ('black' | 'white' | 'gray' | 'red' | 'blue' | 'green' | 'yellow') | null;
          /**
           * Уровень затемнения изображения для лучшей читаемости текста
           */
          imageOverlay?: ('none' | 'light' | 'medium' | 'dark') | null;
          /**
           * Если ссылка внутри сайта, напишите только относительный путь: /city, /city/p (для фильтра по цене), /city/r (для фильтра по рейтингу), /meal и т.п. Полные ссылки только для внешних сайтов.
           */
          link?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Основная информация о вашей компании
   */
  companyInfo: {
    /**
     * Полное юридическое название компании
     */
    legalName: string;
    /**
     * Год основания компании
     */
    year: number;
    /**
     * Основной контактный телефон компании
     */
    phone: string;
    /**
     * ИНН компании (налоговый идентификационный номер)
     */
    inn?: string | null;
    /**
     * Юридический адрес компании
     */
    legalAddress?: string | null;
    /**
     * Загрузите политику конфиденциальности в формате PDF
     */
    privacyPolicyDocument?: (number | null) | Media;
  };
  /**
   * Настройки минимальной суммы заказа(Для физических товаров)
   */
  orderSettings: {
    /**
     * Минимальная сумма заказа для оформления
     */
    minOrderAmount: number;
  };
  /**
   * Ссылки на ваши социальные сети и мессенджеры
   */
  socialLinks: {
    /**
     * Контактный email адрес
     */
    email?: string | null;
    /**
     * Ссылка на страницу ВКонтакте
     */
    vk?: string | null;
    /**
     * Ссылка на Telegram канал или бот
     */
    telegram?: string | null;
    /**
     * Ссылка на whatsApp канал или бота.
     */
    whatsApp?: string | null;
    /**
     * Ссылка на Instagram профиль
     */
    instagram?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Управление городами на сайте. Города используются в URL (например, /moscow/, /piter/)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  /**
   * Список всех городов, доступных на сайте
   */
  cities?:
    | {
        /**
         * Полное название города (например, Москва, Санкт-Петербург)
         */
        name: string;
        /**
         * Уникальный идентификатор для URL (например, moscow, piter). Только латинские буквы, без пробелов
         */
        slug: string;
        /**
         * Склонения названия города для правильного испо  льзования в тексте
         */
        declensions: {
          /**
           * Например: Москва, Санкт-Петербург
           */
          nominative: string;
          /**
           * Например: Москвы, Санкт-Петербурга
           */
          genitive: string;
          /**
           * Например: в Москве, в Санкт-Петербурге
           */
          prepositional: string;
        };
        /**
         * Дополнительный текст для SEO заголовков (например, 'Москва и область')
         */
        seoTitle?: string | null;
        /**
         * Описание для мета-тегов (SEO)
         */
        metaDescription?: string | null;
        /**
         * Этот город будет использоваться при переходе на главную страницу без города в URL
         */
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  homeContent?: T;
  slider?:
    | T
    | {
        slides?:
          | T
          | {
              image?: T;
              title?: T;
              subtitle?: T;
              titleColor?: T;
              subtitleColor?: T;
              imageOverlay?: T;
              link?: T;
              id?: T;
            };
      };
  companyInfo?:
    | T
    | {
        legalName?: T;
        year?: T;
        phone?: T;
        inn?: T;
        legalAddress?: T;
        privacyPolicyDocument?: T;
      };
  orderSettings?:
    | T
    | {
        minOrderAmount?: T;
      };
  socialLinks?:
    | T
    | {
        email?: T;
        vk?: T;
        telegram?: T;
        whatsApp?: T;
        instagram?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  cities?:
    | T
    | {
        name?: T;
        slug?: T;
        declensions?:
          | T
          | {
              nominative?: T;
              genitive?: T;
              prepositional?: T;
            };
        seoTitle?: T;
        metaDescription?: T;
        isDefault?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}